### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by saenzramiro** [MatthieuLemoine/electron-push-receiver#8]
Hello @MatthieuLemoine, thanks for building this library.

It will be really helpful if you can provide a working example of this.

**Comment by MatthieuLemoine** [comment]
Yes it could be useful.

If someone wants to tackle this, feel free to do it.

**Comment by CydeSwype** [comment]
I may try to tackle this over the weekend.  I got it working in my project and it was a real lifesaver (because as far as I know, this module is the only way to do push notifications with electron without having to roll your own servers from scratch).  I didn't find any other modules built on Urban Airship or any other system... so this module is super valuable.  I did struggle at points, mostly navigating some of the terminology of FCM, where to find certain tokens, etc. so I may either build a sample project, record a screencast or both.

**Comment by CydeSwype** [comment]
Just committed this: https://github.com/CydeSwype/electron-fcm-demo/

Let me know if this satisfies the need for example use.  I also captured a screen recording and will try to add voiceover, edit it for brevity and get that posted sometime this week.

**Comment by MatthieuLemoine** [comment]
Nice work @CydeSwype ! Thankd ! I will add a link to your example in the Readme.

**Comment by saenzramiro** [comment]
@CydeSwype Thank you so much! :clap
